config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'comments/create'
  get 'galleries/gallery'
  root "exhibitions#index"
  resources :visits
  resources :tickets
  resources :transactions
  resources :artifacts
  resources :exhibitions
  resources :categories
  resources :galleries
  resources :admins
  devise_for :users
  resources :exhibitions do
    resources :tickets
    resources :comments
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  #root to: 'users/sign_in'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artifact.rb
class Artifact < ApplicationRecord
    mount_uploader :image, ImageUploader 
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :exhibition
  # validates :content, presence: true
end

app/models/exhibition.rb
class Exhibition < ApplicationRecord
    has_many :tickets, dependent: :destroy
    has_many :comments, dependent: :destroy
    mount_uploader :image, ImageUploader
    validates :title, presence: true
    def validate(record)
        if record.start_time > record.end_time
          record.errors.add(:start_time, "Can not be set after the end date and time")
        end
      end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :exhibition
  belongs_to :user
  validates :phone,
    presence: true,
    uniqueness: true,
    length: { maximum: 10 }
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :artifact
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/visit.rb
class Visit < ApplicationRecord
end

app/controllers/artifacts_controller.rb
class ArtifactsController < ApplicationController
  before_action :set_artifact, only: [:show, :edit, :update, :destroy]

  def index
    @artifacts = Artifact.order("name").page(params[:page]).per(2)
  end

  def show
  end

  def new
    @artifact = Artifact.new
  end

  def edit
  end

  def create
    @artifact = Artifact.new(artifact_params)
      if @artifact.save
        redirect_to @artifact, notice: 'Artifact was successfully created.' 
      else
     render :new 
    end
  end

  def update
  
      if @artifact.update(artifact_params)
         redirect_to @artifact, notice: 'Artifact was successfully updated.' 
       
      else
       render :edit
       

    end
  end

  def destroy
    @artifact.destroy
    redirect_to artifacts_url, notice: 'Artifact was successfully destroyed.'
  
  end

  private
    def set_artifact
      @artifact = Artifact.find(params[:id])
    end

    def artifact_params
      params.require(:artifact).permit(:name, :description, :image, :amount, :category, :image_cache)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_exhibition
 before_action :find_comment, only: [:destroy, :edit , :update]
def create
@comment = @exhibition.comments.create(params[:comment].permit(:content))
@comment.save
if @comment.save
  redirect_to exhibition_path(@exhibition)
else
  render 'new'
end
end
def destroy
@comment.destroy
redirect_to exhibition_path(@exhibition)
end
def edit
end
 
def update
if @comment.update(params[:comment].permit(:content))
  redirect_to exhibition_path(@exhibition)
  else
    render 'edit'
  end
end
private
def find_exhibition
  @exhibition = Exhibition.find(params[:exhibition_id])
end
def find_comment
  @comment = @exhibition.comments.find(params[:id])
end

end

app/controllers/exhibitions_controller.rb
class ExhibitionsController < ApplicationController
  before_action :set_exhibition, only: [:show, :edit, :update, :destroy]

  def index
    @exhibitions = Exhibition.order("title").page(params[:page]).per(5)
  end

  def show
    @comments = Comment.where(exhibition_id: @exhibition)
  end

  def new
    @exhibition = Exhibition.new
  end

  def edit
  end

  def create
    @exhibition = Exhibition.new(exhibition_params)
    if @exhibition.save
     redirect_to @exhibition, notice: 'Exhibition was successfully created.' 
    else
      render :new 
    end
  end

  def update
    
      if @exhibition.update(exhibition_params)
       redirect_to @exhibition, notice: 'Exhibition was successfully updated.' 
      else
        render :edit
      end
  end

  def destroy
    @exhibition.destroy
   
     redirect_to exhibitions_url, notice: 'Exhibition was successfully destroyed.' 
  
  end

  private
    
    def set_exhibition
      @exhibition = Exhibition.find(params[:id])
    end

    def exhibition_params
      params.require(:exhibition).permit(:image, :title, :date, :start_time, :discription, :end_time, :image_cache)
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  def index
    @tickets = Ticket.all
  end

  def show
  end

  def new
    @exhibition=Exhibition.find(params[:exhibition_id])
    @ticket = @exhibition.tickets.build
  
  end

  def edit
  end

  def create
    @ticket = Ticket.new(ticket_params)

      if @ticket.save
        ContactMailer.contact_mail(@ticket).deliver
       redirect_to @ticket, notice: 'Ticket was successfully created.' 
        
      else
         render :new 
       
      end
  end

  def update
   
      if @ticket.update(ticket_params)
       redirect_to @ticket, notice: 'Ticket was successfully updated.' 
      else
       render :edit 
    end
  end

  def destroy
    @ticket.destroy
   
      redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' 
    
  end

  private
   
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end
    def ticket_params
      params.require(:ticket).permit(:phone, :exhibition_id, :user_id)
    end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :set_visit, only: [:show, :edit, :update, :destroy]

  def index
    @visits = Visit.all
  end

  def show
  end

  def new
    @visit = Visit.new
  end
  def edit
  end

  def create
    @visit = Visit.new(visit_params)
    if @visit.save
      redirect_to @visit, notice: 'Visit was successfully created.' 
    else
      render :new   
    end
  end

  def update
    if @visit.update(visit_params)
      redirect_to @visit, notice: 'Visit was successfully updated.' 
    else
      render :edit 
    end
  end
  def destroy
    @visit.destroy
    redirect_to visits_url, notice: 'Visit was successfully destroyed.' 
  end
  private
    def set_visit
      @visit = Visit.find(params[:id])
    end
    def visit_params
      params.require(:visit).permit(:day_week, :start_time, :end_time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artifacts_helper.rb
module ArtifactsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/exhibitions_helper.rb
module ExhibitionsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/exhibitions/_form.html.erb
<%= form_with(model: exhibition, local: true) do |form| %>
  <% if exhibition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(exhibition.errors.count, "error") %> prohibited this exhibition from being saved:</h2>

      <ul>
      <% exhibition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :image %>
    <%= image_tag(@exhibition.image.url) if @exhibition.image && @exhibition.image.url %>
    <%= form.file_field :image, class: 'form-control' %>
    <%= form.hidden_field :image_cache %>
  </div>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :date %>
    <%= form.date_select :date, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :start_time %>
    <%= form.time_select :start_time, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :discription %>
    <%= form.text_area :discription, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :end_time %>
    <%= form.time_select :end_time, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/exhibitions/edit.html.erb
<h1>Editing Exhibition</h1>

<%= render 'form', exhibition: @exhibition %>

<%= link_to 'Show', @exhibition %> |
<%= link_to 'Back', exhibitions_path %>

app/views/exhibitions/index.html.erb
<p id="notice"><%= notice %></p>
<div class="col-sm-6">
    <h1>Exhibitions</h1>
  </div>


<%= paginate @exhibitions %>
<br>


<div class="container my-4">
      <div class="carousel-inner" role="listbox">
<% @exhibitions.each do |exhibition| %>
        <!--First slide-->
        <div class="carousel-item active">
          <div class="row">
            <div class="col-md-4">
            <h4 class="card-title"><%= exhibition.title %></h4>
              <div class="card mb-2">
               <td><% if exhibition.image_url %>
    <%= image_tag exhibition.image_url, size: "350x200" %>
 <% end %>
                <div class="card-body">
                  <h4 class="card-title"><%= exhibition.date %></h4>
                  <p class="card-text">start time:<h4><%= exhibition.start_time %></p><br>
                 <p class="card-text">End time:</h4> <%= exhibition.end_time %></h4></p>
                  <a class="btn btn-primary">Button</a>
                  <p class="card-text"><h4><%= exhibition.discription %></h4>
                  <%=link_to "ATTEND EVENT", new_exhibition_ticket_path(exhibition)%>
                  <td><%= link_to 'Show', exhibition %></td>
        
                </div>
                <% if user_signed_in? %>
        <% if current_user.admin? %>
        <td><%= link_to 'Edit', edit_exhibition_path(exhibition) %></td>
        <td><%= link_to 'Destroy', exhibition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%= link_to 'New Exhibition', new_exhibition_path %>
        <% end %>
        <% end %> 
              </div>
            </div>
            
 <% end %>            

        </div>
        </div>
        </div>
        <!--/.Third slide-->

      </div>
      <!--/.Slides-->

    </div>
    <!--/.Carousel Wrapper-->


  </div>

app/views/exhibitions/new.html.erb
<h1>New Exhibition</h1>

<%= render 'form', exhibition: @exhibition %>

<%= link_to 'Back', exhibitions_path %>

app/views/exhibitions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>image:</strong>
  <%= image_tag @exhibition.image.url, class: "", size: "200x200" unless @exhibition.image.url.blank? %>
</p>

<p>
  <strong>Title:</strong>
  <%= @exhibition.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @exhibition.date %>
</p>

<p>
  <strong>Start Time:</strong>
  <%= @exhibition.start_time %>
</p>
<p>
  <strong>Discription:</strong>
  <%= @exhibition.discription %>
</p>
<p>
  <strong>End Time:</strong>
  <%= @exhibition.end_time %>
</p>
<p>List of Comments(Contents below are important)</p>
<%= render 'comments/comment' %>
<% if user_signed_in? %>
  <% if current_user.admin? %>
<%= link_to 'Edit', edit_exhibition_path(@exhibition) %> |
<%= link_to 'Back', exhibitions_path %>
<% end %>
<% end %>