config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'comments/create'
  get 'galleries/gallery'
  root "exhibitions#index"
  resources :visits
  resources :tickets
  resources :transactions
  resources :artifacts
  resources :exhibitions
  resources :categories
  resources :galleries
  resources :admins
  devise_for :users
  resources :exhibitions do
    resources :tickets
    resources :comments
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  #root to: 'users/sign_in'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artifact.rb
class Artifact < ApplicationRecord
    mount_uploader :image, ImageUploader 
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :exhibition
  # validates :content, presence: true
end

app/models/exhibition.rb
class Exhibition < ApplicationRecord
    has_many :tickets, dependent: :destroy
    has_many :comments, dependent: :destroy
    mount_uploader :image, ImageUploader
    validates :title, presence: true
    def validate(record)
        if record.start_time > record.end_time
          record.errors.add(:start_time, "Can not be set after the end date and time")
        end
      end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :exhibition
  belongs_to :user
  validates :phone,
    presence: true,
    uniqueness: true,
    length: { maximum: 10 }
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :artifact
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/visit.rb
class Visit < ApplicationRecord
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_exhibition
 before_action :find_comment, only: [:destroy, :edit , :update]
def create
@comment = @exhibition.comments.create(params[:comment].permit(:content))
@comment.save
if @comment.save
  redirect_to exhibition_path(@exhibition)
else
  render 'new'
end
end
def destroy
@comment.destroy
redirect_to exhibition_path(@exhibition)
end
def edit
end
 
def update
if @comment.update(params[:comment].permit(:content))
  redirect_to exhibition_path(@exhibition)
  else
    render 'edit'
  end
end
private
def find_exhibition
  @exhibition = Exhibition.find(params[:exhibition_id])
end
def find_comment
  @comment = @exhibition.comments.find(params[:id])
end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  def index
    @tickets = Ticket.all
  end

  def show
  end

  def new
    @exhibition=Exhibition.find(params[:exhibition_id])
    @ticket = @exhibition.tickets.build
  
  end

  def edit
  end

  def create
    @ticket = Ticket.new(ticket_params)

      if @ticket.save
        ContactMailer.contact_mail(@ticket).deliver
       redirect_to @ticket, notice: 'Ticket was successfully created.' 
        
      else
         render :new 
       
      end
  end

  def update
   
      if @ticket.update(ticket_params)
       redirect_to @ticket, notice: 'Ticket was successfully updated.' 
      else
       render :edit 
    end
  end

  def destroy
    @ticket.destroy
   
      redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' 
    
  end

  private
   
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end
    def ticket_params
      params.require(:ticket).permit(:phone, :exhibition_id, :user_id)
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  def index
    @transactions = Transaction.all
  end

  def show
  end

  def new
    @transaction = Transaction.new
  end

  def edit
  end

  def create
    @transaction = Transaction.new(transaction_params)

      if @transaction.save
        redirect_to @transaction, notice: 'Transaction was successfully created.' 
       
      else
        render :new 
    end
  end

  def update
   
      if @transaction.update(transaction_params)
      redirect_to @transaction, notice: 'Transaction was successfully updated.' 
  
      else
        render :edit 
       
      end
  end


  def destroy
    @transaction.destroy
       redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' 
  end
  private
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end
    def transaction_params
      params.require(:transaction).permit(:user_id, :artifact_id, :amaunt, :currency, :status, :details)
    end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :set_visit, only: [:show, :edit, :update, :destroy]

  def index
    @visits = Visit.all
  end

  def show
  end

  def new
    @visit = Visit.new
  end
  def edit
  end

  def create
    @visit = Visit.new(visit_params)
    if @visit.save
      redirect_to @visit, notice: 'Visit was successfully created.' 
    else
      render :new   
    end
  end

  def update
    if @visit.update(visit_params)
      redirect_to @visit, notice: 'Visit was successfully updated.' 
    else
      render :edit 
    end
  end
  def destroy
    @visit.destroy
    redirect_to visits_url, notice: 'Visit was successfully destroyed.' 
  end
  private
    def set_visit
      @visit = Visit.find(params[:id])
    end
    def visit_params
      params.require(:visit).permit(:day_week, :start_time, :end_time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artifacts_helper.rb
module ArtifactsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/exhibitions_helper.rb
module ExhibitionsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction, local: true) do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :artifact_id %>
    <%= form.text_field :artifact_id %>
  </div>

  <div class="field">
    <%= form.label :amaunt %>
    <%= form.text_field :amaunt %>
  </div>

  <div class="field">
    <%= form.label :currency %>
    <%= form.text_field :currency %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :details %>
    <%= form.text_area :details %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transactions</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Artifact</th>
      <th>Amaunt</th>
      <th>Currency</th>
      <th>Status</th>
      <th>Details</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.user %></td>
        <td><%= transaction.artifact %></td>
        <td><%= transaction.amaunt %></td>
        <td><%= transaction.currency %></td>
        <td><%= transaction.status %></td>
        <td><%= transaction.details %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @transaction.user %>
</p>

<p>
  <strong>Artifact:</strong>
  <%= @transaction.artifact %>
</p>

<p>
  <strong>Amaunt:</strong>
  <%= @transaction.amaunt %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @transaction.currency %>
</p>

<p>
  <strong>Status:</strong>
  <%= @transaction.status %>
</p>

<p>
  <strong>Details:</strong>
  <%= @transaction.details %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>