config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'comments/create'
  get 'galleries/gallery'
  root "exhibitions#index"
  resources :visits
  resources :tickets
  resources :transactions
  resources :artifacts
  resources :exhibitions
  resources :categories
  resources :galleries
  resources :admins
  devise_for :users
  resources :exhibitions do
    resources :tickets
    resources :comments
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  #root to: 'users/sign_in'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artifact.rb
class Artifact < ApplicationRecord
    mount_uploader :image, ImageUploader 
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :exhibition
  # validates :content, presence: true
end

app/models/exhibition.rb
class Exhibition < ApplicationRecord
    has_many :tickets, dependent: :destroy
    has_many :comments, dependent: :destroy
    mount_uploader :image, ImageUploader
    validates :title, presence: true
    def validate(record)
        if record.start_time > record.end_time
          record.errors.add(:start_time, "Can not be set after the end date and time")
        end
      end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :exhibition
  belongs_to :user
  validates :phone,
    presence: true,
    uniqueness: true,
    length: { maximum: 10 }
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :artifact
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/visit.rb
class Visit < ApplicationRecord
end

app/controllers/artifacts_controller.rb
class ArtifactsController < ApplicationController
  before_action :set_artifact, only: [:show, :edit, :update, :destroy]

  def index
    @artifacts = Artifact.order("name").page(params[:page]).per(2)
  end

  def show
  end

  def new
    @artifact = Artifact.new
  end

  def edit
  end

  def create
    @artifact = Artifact.new(artifact_params)
      if @artifact.save
        redirect_to @artifact, notice: 'Artifact was successfully created.' 
      else
     render :new 
    end
  end

  def update
  
      if @artifact.update(artifact_params)
         redirect_to @artifact, notice: 'Artifact was successfully updated.' 
       
      else
       render :edit
       

    end
  end

  def destroy
    @artifact.destroy
    redirect_to artifacts_url, notice: 'Artifact was successfully destroyed.'
  
  end

  private
    def set_artifact
      @artifact = Artifact.find(params[:id])
    end

    def artifact_params
      params.require(:artifact).permit(:name, :description, :image, :amount, :category, :image_cache)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_exhibition
 before_action :find_comment, only: [:destroy, :edit , :update]
def create
@comment = @exhibition.comments.create(params[:comment].permit(:content))
@comment.save
if @comment.save
  redirect_to exhibition_path(@exhibition)
else
  render 'new'
end
end
def destroy
@comment.destroy
redirect_to exhibition_path(@exhibition)
end
def edit
end
 
def update
if @comment.update(params[:comment].permit(:content))
  redirect_to exhibition_path(@exhibition)
  else
    render 'edit'
  end
end
private
def find_exhibition
  @exhibition = Exhibition.find(params[:exhibition_id])
end
def find_comment
  @comment = @exhibition.comments.find(params[:id])
end

end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def gallery
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  def index
    @tickets = Ticket.all
  end

  def show
  end

  def new
    @exhibition=Exhibition.find(params[:exhibition_id])
    @ticket = @exhibition.tickets.build
  
  end

  def edit
  end

  def create
    @ticket = Ticket.new(ticket_params)

      if @ticket.save
        ContactMailer.contact_mail(@ticket).deliver
       redirect_to @ticket, notice: 'Ticket was successfully created.' 
        
      else
         render :new 
       
      end
  end

  def update
   
      if @ticket.update(ticket_params)
       redirect_to @ticket, notice: 'Ticket was successfully updated.' 
      else
       render :edit 
    end
  end

  def destroy
    @ticket.destroy
   
      redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' 
    
  end

  private
   
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end
    def ticket_params
      params.require(:ticket).permit(:phone, :exhibition_id, :user_id)
    end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :set_visit, only: [:show, :edit, :update, :destroy]

  def index
    @visits = Visit.all
  end

  def show
  end

  def new
    @visit = Visit.new
  end
  def edit
  end

  def create
    @visit = Visit.new(visit_params)
    if @visit.save
      redirect_to @visit, notice: 'Visit was successfully created.' 
    else
      render :new   
    end
  end

  def update
    if @visit.update(visit_params)
      redirect_to @visit, notice: 'Visit was successfully updated.' 
    else
      render :edit 
    end
  end
  def destroy
    @visit.destroy
    redirect_to visits_url, notice: 'Visit was successfully destroyed.' 
  end
  private
    def set_visit
      @visit = Visit.find(params[:id])
    end
    def visit_params
      params.require(:visit).permit(:day_week, :start_time, :end_time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artifacts_helper.rb
module ArtifactsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/exhibitions_helper.rb
module ExhibitionsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/artifacts/_form.html.erb
<%= form_with(model: artifact, local: true) do |form| %>
  <% if artifact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artifact.errors.count, "error") %> prohibited this artifact from being saved:</h2>

      <ul>
      <% artifact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= image_tag(@artifact.image.url) if @artifact.image && @artifact.image.url %>
    <%= form.file_field :image, class: 'form-control' %>
    <%= form.hidden_field :image_cache %>
  </div>

  <div class="form-group">
    <%= form.label :amount %>
    <%= form.text_field :amount, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :category %>
    <%= form.text_field :category, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/artifacts/edit.html.erb
<h1>Editing Artifact</h1>

<%= render 'form', artifact: @artifact %>

<%= link_to 'Show', @artifact %> |
<%= link_to 'Back', artifacts_path %>

app/views/artifacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Artifacts</h1>

<%= paginate @artifacts %>
<br>
  <div class="container my-4">
      <div class="carousel-inner" role="listbox">
<% @artifacts.each do |artifact| %>
        <!--First slide-->
        <div class="carousel-item active">
          <div class="row">
            <div class="col-md-4">
              <div class="card mb-2">
               <td><% if artifact.image_url %>
               <%= image_tag artifact.image_url, size:"200x100" %>
               <% end %>
                <div class="card-body">
                  <h4 class="card-title"><%= artifact.name %></h4>
                  <p class="card-text"><%= artifact.description %></p>
                   <p class="card-text"><%= artifact.amount %></p>
                    <p class="card-text"><%= artifact.category %></p>
                  <a class="btn btn-primary">Button</a>
                  <%= search_form_for @q, remote: true do |f| %>
                    <%= f.label :name, 'name' %>
                    <%= f.search_field :name %>
                    <%= f.submit %>
                  <% end %>
                   <% if user_signed_in? %>
                    <% if current_user.admin?%>
                  <%= link_to 'New Artifact', new_artifact_path class="btn btn-primary" %>
                  <% end %>
                  <% end %> 
                </div>
                 
              </div>
            </div>
 <% end %>            

        </div>
        </div>
        </div>
        <!--/.Third slide-->

      </div>
      <!--/.Slides-->

    </div>
    <!--/.Carousel Wrapper-->


  </div>

app/views/artifacts/new.html.erb
<h1>New Artifact</h1>

<%= render 'form', artifact: @artifact %>

<%= link_to 'Back', artifacts_path %>

app/views/comments/_comment.html.erb
<div class="card-body">
  <% @comments.each do |comment| %>
    <% if comment.id.present? %>
      <div class="card" style="width:18rem">
      <p class="card-text"></br><%= comment.content %><br></p></br>
        </div><br>
        <% if user_signed_in? %>
            <% if current_user.admin? %>
        <%= link_to "delete", [comment.exhibition, comment], method: :delete, class:"genric-btn danger-border circle" %>
        <%= link_to "edit ", edit_exhibition_comment_path(comment.exhibition, comment), class:"genric-btn success-border circle" %></p>
        <% end %>
        <% end %>
        </h4>
    <% end %>
  <% end %>
<%= render 'comments/form'%>
</div>

app/views/comments/_form.html.erb
<%= form_for ([@exhibition, @exhibition.comments.build]) do |f| %>
    <%= f.text_area :content, class:"single-input", placeholder:"enter comment",required:true %>
    <%= f.submit "exhibition comment", class:"btn btn-primary" %>
    <% end %>

app/views/comments/_index.html.erb
<div class="card-body">
  <% @comments.each do |comment| %>
    <% if comment.id.present? %>
      
      <h4 class="card-title"><%= comment.content %></h4>
      
    <% end %>
  <% end %>
  </div>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/edit.html.erb
<%= form_for ([@exhibition, @comment]) do |f| %>
    <%= f.text_area :content, class:"single-input"%>
    <%= f.submit "exhibition comment", class:"genric-btn info-border circle" %>
      <%end%>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.blog.comments, blog: @comment.blog }) %>")
$("textarea").val('')

app/views/tickets/_form.html.erb
<%= form_with(model: ticket, local: true) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="form-group">
    <%= form.label :phone %>
    <%= form.text_field :phone, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%# <%= form.label :exhibition_id %>
    <%= form.hidden_field :exhibition_id, class: 'form-control' %>
  </div>

  <div class="form-group">
  <%  if user_signed_in? %>
    <%= form.hidden_field :user_id, value: current_user.id%>
    <%end%>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tickets</h1>

<table>
  <thead>
    <tr>
      <th>Phone</th>
      <th>Exhibition</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.phone %></td>
        <td><%= ticket.exhibition %></td>
        <td><%= ticket.user %></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Phone:</strong>
  <%= @ticket.phone %>
</p>

<p>
  <strong>Exhibition:</strong>
  <%= @ticket.exhibition %>
</p>

<p>
  <strong>User:</strong>
  <%= @ticket.user %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>

app/views/visits/_form.html.erb
<%= form_with(model: visit, local: true) do |form| %>
  <% if visit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
      <% visit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :day_week %>
    <%= form.text_area :day_week, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :start_time %>
    <%= form.time_select :start_time, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :end_time %>
    <%= form.time_select :end_time, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/visits/edit.html.erb
<h1>Editing Visit</h1>

<%= render 'form', visit: @visit %>

<%= link_to 'Show', @visit %> |
<%= link_to 'Back', visits_path %>

app/views/visits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Visits</h1>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Day week</th>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @visits.each do |visit| %>
      <tr>
        <td><%= visit.day_week %></td>
        <td><%= visit.start_time %></td>
        <td><%= visit.end_time %></td>
        <td><%= link_to 'Show', visit %></td>
        <td><%= link_to 'Edit', edit_visit_path(visit) %></td>
        <td><%= link_to 'Destroy', visit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'New Visit', new_visit_path %>
<!--Carousel Wrapper-->
<div id="multi-item-example" class="carousel slide carousel-multi-item carousel-multi-item-2" data-ride="carousel">

  <!--Controls-->
  <div class="controls-top">
    <a class="black-text" href="#multi-item-example" data-slide="prev"><i class="fas fa-angle-left fa-3x pr-3"></i></a>
    <a class="black-text" href="#multi-item-example" data-slide="next"><i class="fas fa-angle-right fa-3x pl-3"></i></a>
  </div>
  <!--/.Controls-->

  <!--Slides-->
  <div class="carousel-inner" role="listbox">

    <!--First slide-->
    <div class="carousel-item active">

      <div class="col-md-3 mb-3">
        <div class="card">
          <img class="img-fluid" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(38).jpg"
            alt="Card image cap">
        </div>
      </div>

      <div class="col-md-3 mb-3">
        <div class="card">
          <img class="img-fluid" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(19).jpg"
            alt="Card image cap">
        </div>
      </div>

      <div class="col-md-3 mb-3">
        <div class="card">
          <img class="img-fluid" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(42).jpg"
            alt="Card image cap">
        </div>
      </div>

      <div class="col-md-3 mb-3">
        <div class="card">
          <img class="img-fluid" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(8).jpg"
            alt="Card image cap">
        </div>
      </div>

    </div>
    <!--/.First slide-->

    <!--Second slide-->
    <div class="carousel-item">

      <div class="col-md-3 mb-3">
        <div class="card">
          <p id="notice"><%= notice %></p>
<div id="multi-item-example">
          <img class="img-fluid" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(26).jpg"
            alt="Card image cap">
        </div>
      </div>

      <div class="col-md-3 mb-3">
        <div class="card">
          <img class="img-fluid" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(25).jpg"
            alt="Card image cap">
        </div>
      </div>

      <div class="col-md-3 mb-3">
        <div class="card">
          <img class="img-fluid" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(47).jpg"
            alt="Card image cap">
        </div>
      </div>

      <div class="col-md-3 mb-3">
        <div class="card">
          <img class="img-fluid" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(26).jpg"
            alt="Card image cap">
        </div>
      </div>

    </div>
    <!--/.Second slide-->

    <!--Third slide-->
    <div class="carousel-item">

      <div class="col-md-3 mb-3">
        <div class="card">
          <img class="img-fluid" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(64).jpg"
            alt="Card image cap">
        </div>
      </div>

      <div class="col-md-3 mb-3">
        <div class="card">
          <img class="img-fluid" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(51).jpg"
            alt="Card image cap">
        </div>
      </div>

      <div class="col-md-3 mb-3">
        <div class="card">
          <img class="img-fluid" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(59).jpg"
            alt="Card image cap">
        </div>
      </div>

      <div class="col-md-3 mb-3">
        <div class="card">
          <img class="img-fluid" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(63).jpg"
            alt="Card image cap">
        </div>
      </div>

    </div>
    <!--/.Third slide-->

  </div>
  <!--/.Slides-->

</div>
<!--/.Carousel Wrapper-->
 <hr class="my-4">

    <!--Carousel Wrapper-->
    <div id="multi-item-example" class="carousel slide carousel-multi-item" data-ride="carousel">

      <!--Controls-->
      <div class="controls-top">
        <a class="btn-floating" href="#multi-item-example" data-slide="prev"><i class="fa fa-chevron-left"></i></a>
        <a class="btn-floating" href="#multi-item-example" data-slide="next"><i class="fa fa-chevron-right"></i></a>
      </div>
      <!--/.Controls-->

      <!--Indicators-->
      <ol class="carousel-indicators">
        <li data-target="#multi-item-example" data-slide-to="0" class="active"></li>
        <li data-target="#multi-item-example" data-slide-to="1"></li>
        <li data-target="#multi-item-example" data-slide-to="2"></li>
      </ol>
      <!--/.Indicators-->

      <!--Slides-->
      <div class="carousel-inner" role="listbox">

        <!--First slide-->
        <div class="carousel-item active">

          <div class="row">
            <div class="col-md-4">
              <div class="card mb-2">
                <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(34).jpg"
                  alt="Card image cap">
                <div class="card-body">
                  <h4 class="card-title">Card title</h4>
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                    card's content.</p>
                  <a class="btn btn-primary">Button</a>
                </div>
              </div>
            </div>

            <div class="col-md-4 clearfix d-none d-md-block">
              <div class="card mb-2">
                <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(18).jpg"
                  alt="Card image cap">
                <div class="card-body">
                  <h4 class="card-title">Card title</h4>
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                    card's content.</p>
                  <a class="btn btn-primary">Button</a>
                </div>
              </div>
            </div>

            <div class="col-md-4 clearfix d-none d-md-block">
              <div class="card mb-2">
                <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(35).jpg"
                  alt="Card image cap">
                <div class="card-body">
                  <h4 class="card-title">Card title</h4>
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                    card's content.</p>
                  <a class="btn btn-primary">Button</a>
                </div>
              </div>
            </div>
          </div>

        </div>
        <!--/.First slide-->

        <!--Second slide-->
        <div class="carousel-item">

          <div class="row">
            <div class="col-md-4">
              <div class="card mb-2">
                <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Horizontal/City/4-col/img%20(60).jpg"
                  alt="Card image cap">
                <div class="card-body">
                  <h4 class="card-title">Card title</h4>
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                    card's content.</p>
                  <a class="btn btn-primary">Button</a>
                </div>
              </div>
            </div>

            <div class="col-md-4 clearfix d-none d-md-block">
              <div class="card mb-2">
                <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Horizontal/City/4-col/img%20(47).jpg"
                  alt="Card image cap">
                <div class="card-body">
                  <h4 class="card-title">Card title</h4>
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                    card's content.</p>
                  <a class="btn btn-primary">Button</a>
                </div>
              </div>
            </div>

            <div class="col-md-4 clearfix d-none d-md-block">
              <div class="card mb-2">
                <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Horizontal/City/4-col/img%20(48).jpg"
                  alt="Card image cap">
                <div class="card-body">
                  <h4 class="card-title">Card title</h4>
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                    card's content.</p>
                  <a class="btn btn-primary">Button</a>
                </div>
              </div>
            </div>
          </div>

        </div>
        <!--/.Second slide-->

        <!--Third slide-->
        <div class="carousel-item">

          <div class="row">
            <div class="col-md-4">
              <div class="card mb-2">
                <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Horizontal/Food/4-col/img%20(53).jpg"
                  alt="Card image cap">
                <div class="card-body">
                  <h4 class="card-title">Card title</h4>
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                    card's content.</p>
                  <a class="btn btn-primary">Button</a>
                </div>
              </div>
            </div>

            <div class="col-md-4 clearfix d-none d-md-block">
              <div class="card mb-2">
                <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Horizontal/Food/4-col/img%20(45).jpg"
                  alt="Card image cap">
                <div class="card-body">
                  <h4 class="card-title">Card title</h4>
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                    card's content.</p>
                  <a class="btn btn-primary">Button</a>
                </div>
              </div>
            </div>

            <div class="col-md-4 clearfix d-none d-md-block">
              <div class="card mb-2">
                <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Horizontal/Food/4-col/img%20(51).jpg"
                  alt="Card image cap">
                <div class="card-body">
                  <h4 class="card-title">Card title</h4>
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                    card's content.</p>
                  <a class="btn btn-primary">Button</a>
                </div>
              </div>
            </div>
          </div>

        </div>
        <!--/.Third slide-->

      </div>
      <!--/.Slides-->

    </div>
    <!--/.Carousel Wrapper-->


  </div>

app/views/visits/new.html.erb
<h1>New Visit</h1>

<%= render 'form', visit: @visit %>

<%= link_to 'Back', visits_path %>

app/views/visits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Day week:</strong>
  <%= @visit.day_week %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @visit.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @visit.end_time %>
</p>

<%= link_to 'Edit', edit_visit_path(@visit) %> |
<%= link_to 'Back', visits_path %>